name: PHP CS Fixer

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  php-cs-fixer:
    name: Run PHP CS Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Cambia esto a tu versión de PHP
          tools: php-cs-fixer

      - name: Check PHP code style
        run: php-cs-fixer fix --dry-run --diff --diff-format=udiff
